describe("checks tool reservation path", () => {
  beforeEach(() => {
    cy.viewport(1280, 720);
    cy.visit("http://localhost:5173/")
      .get("header nav div")
      .find("a[href='/login']")
      .click()
      .get("form")
      .find("input[type='email']")
      .should("exist")
      .type("martynas@mail.com")
      .get("form")
      .find("input[type='password']")
      .should("exist")
      .type("testuoju123")
      .get("form")
      .find("button")
      .click()
      .get("header nav div span")
      .should("contain.text", "Welcome");
  });
  it("checks admin panel tools dashboard create edit delete", () => {
    cy.get("header nav div")
      .find("a[href='/admin']")
      .click()
      .get("h2")
      .should("exist")
      .should("contain.text", "Admin panel")
      .get("a[href='/admin/tools']")
      .click()
      .get("a[href='/admin/tools/new']")
      .click()
      .get("div[id='description.nameRetail_display']")
      .dblclick()
      .get("textarea[id='description.nameRetail_textarea']")
      .clear()
      .type("cypress test")
      .type("{enter}")
      .get("button")
      .contains("Add new item")
      .click()
      .visit("http://localhost:5173/admin/tools/")
      .get("a div p")
      .contains("cypress test")
      .click()
      .get("div[id='description.basePrice_display']")
      .dblclick()
      .get("textarea[id='description.basePrice_textarea']")
      .clear()
      .type("1234321")
      .type("{enter}")
      .get("button")
      .contains("Save changes")
      .click()
      .visit("http://localhost:5173/admin/tools/")
      .get("a div p")
      .contains("1234321")
      .click()
      .get("button")
      .contains("Delete")
      .click()
      .visit("http://localhost:5173/admin/tools/")
      .get("a div p")
      .should("not.contain.text", "1234321");
  });
  it("checks admin panel reservations dashboard create edit delete", () => {
    cy.get("header nav div")
      .find("a[href='/admin']")
      .click()
      .get("h2")
      .should("exist")
      .should("contain.text", "Admin panel")
      .get("a[href='/admin/reservations']")
      .click()
      .get("button")
      .contains("Create Reservation")
      .click()
      .get("form")
      .find('select[name="tool"]')
      .select(1)
      .get("form")
      .find('select[name="userId"]')
      .select("674701cfb3f8499acd91488f")
      .get("form")
      .find('input[name="contactName"]')
      .type("cypress test")
      .get("form")
      .find('input[name="contactEmail"]')
      .type("cypress@test.com")
      .get("form")
      .find('input[name="contactPhone"]')
      .type("+12345678987")
      .get("form")
      .find('select[name="pickupLocation"]')
      .select(4)
      .get("form")
      .find('input[name="dateRange.from"]')
      .type("2025-11-11")
      .get("form")
      .find('input[name="dateRange.to"]')
      .type("2025-12-11")
      .get("form button")
      .contains("Create Reservation")
      .click()
      .visit("http://localhost:5173/admin/reservations")
      .get("table tr td")
      .contains("cypress test")
      .click()
      .get('a[href^="/admin/reservations/edit/"]')
      .click()
      .get("form")
      .find('input[name="contactName"]')
      .clear()
      .type("cypress edit")
      .get("button")
      .contains("Save Changes")
      .click()
      .visit("http://localhost:5173/admin/reservations")
      .get("table tr")
      .contains("cypress edit")
      .should("exist")
      .parent()
      .find("button")
      .click()
      .visit("http://localhost:5173/admin/reservations")
      .get("table tr td")
      .should("not.contain.text", "cypress edit");
  });
  it("checks admin panel reservations dashboard create edit delete", () => {
    cy.get("header nav div")
      .find("a[href='/admin']")
      .click()
      .get("h2")
      .should("exist")
      .should("contain.text", "Admin panel")
      .get("a[href='/admin/users']")
      .click()
      .get("button")
      .contains("Add New User")
      .click()
      .get("form")
      .find('input[name="name"]')
      .type("cypress test")
      .get("form")
      .find('input[name="email"]')
      .type("cypress2@test.com")
      .get("form")
      .find('input[name="password"]')
      .type("test123")
      .get("form")
      .find('input[name="phoneNumber"]')
      .type("+12345678987")
      .get("form")
      .find('input[name="dateOfBirth"]')
      .type("1995-12-11")
      .get("form")
      .find('input[name="address"]')
      .type("house")
      .get("form button")
      .contains("Create User")
      .click()
      .visit("http://localhost:5173/admin/users")
      .get("table tr td")
      .contains("cypress test")
      .parent()
      .parent()
      .find('a[href^="/admin/users/edit/"]')
      .click()
      .get("form")
      .find('input[name="name"]')
      .clear()
      .type("cypress edit")
      .get("button")
      .contains("Save Changes")
      .click()
      .visit("http://localhost:5173/admin/users")
      .get("table tr")
      .contains("cypress edit")
      .should("exist")
      .parent()
      .parent()
      .find("button")
      .contains("Delete")
      .click()
      .type("{enter}")
      .visit("http://localhost:5173/admin/users")
      .get("table tr td")
      .should("not.contain.text", "cypress edit");
  });
});
