import mongoose from 'mongoose';
const Schema = mongoose.Schema;

const toolsSchema = new Schema({
  toolType: { type: String, required: true },
  description: {
    nameRetail: { type: String, required: true },
    basePrice: { type: String, required: true },
    imageURIs: [String],
    details: {
      productType:{type: String, required: true},
      trademark:{type: String, required: true},
      model: String,
      generator_type: String,
      engine_type: String,
      fuel_type: String,
      power: Number,
      max_power: Number,
      nom_power: Number,
      noise_level: Number,
      fuel_container: Number,
      fuel_consumption: Number,
      starter_type: String,
      alternating_current: Number,
      oil_level_safety: Boolean,
      over_voltage_safety: Boolean,
      work_time: Number,
      single_phase_connection_number: Number,
      voltmeter: Boolean,
      voltage_regulator: Boolean,
      has_wheels: Boolean,
      length: Number,
      has_handles: Boolean,
      width: Number,
      height: Number,
      weight: Number,
      rotatios_per_minute: Number,
      impacts_per_minute: String,
      impact_energy: Number,
      type_of_cartrige: String,
      max_drill_diameter_cement: String,
      max_drill_diameter_wood: String,
      max_drill_diameter_metal: String,
      cable_length: Number,
      depth_protection: Boolean,
      drilling_with_impact: Boolean,
      drilling_without_impact: Boolean,
      rotations_per_minuite: Number,
      max_mill_depth: Number,
      container_size: Number,
      dry_vacuum: Boolean,
      liquid_vacuum: Boolean,
      vacuum_type: String,
      chainsaw_type: String,
      motor_type: String,
      anti_vibration: Boolean,
      chain_brakes: String,
      charger: Boolean,
      requires_batery: Boolean,
      chain_step: String,
      power_supply_type: String,
      saw_blade_diameter: String,
      rotation_angle: String,
      saw_hole_diameter: String,
      adjustable_support: Boolean,
      additional_information: String,
      warranty: {type: Number, required: true},
      company_warranty: {type: Number, required: true},
      origin_country: {type: String, required: true}
    }
  },
  isAvailable: { type: Boolean, required: true },
  isVisible: { type: Boolean, default: true },
  isDraft: { type: Boolean, required: true },
  reservation: [{ type: String, default: '' }],
  reviews: [{ type: String, default: '' }]
}, {timestamps: {createdAt: "createdAt"}});

export default mongoose.model('Tools', toolsSchema);